### ISSUE TITLE
Can u update the support to bleve/v2?

### ISSUE THREAD

**Issue by wolf1860** [ttys3/gojieba-bleve#2]
Thanks a lot.

**Comment by smarteng** [comment]
同求支持 v2版本

**Comment by ttys3** [comment]
updated @smarteng  @wolf1860 

ref:  https://github.com/blevesearch/bleve/issues/1495

https://blevesearch.com/news/Bleve-v2.0.0-Released/

**Comment by ttys3** [comment]
problem has resolved.

close due to non active for a long time.
